<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZY2zoNV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZY2zoNV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZY2zoNV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZY2zoNV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZY2zoNV\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZY2zoNV',
    'container.build_id' => '1e5f0f1f',
    'container.build_time' => 1652971184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZY2zoNV');
